### ISSUE TITLE
[Feature Request] Adding barcode scanning functionality?

### ISSUE THREAD

**Issue by ianbroad** [mebjas/html5-qrcode#133] opened 2020-11-04 18:52 UTC
Has there been any thought on adding barcode scanning functionality as well to this library?

**Comment by mebjas** [comment] 2020-11-22 13:29
@ianbroad 

I have created a prototype which should be able to scan some barcodes, can you give it a try?

You can try out the demo here: https://blog.minhazav.dev/research/html5-qrcode-beta 
Here's the minified code to experiment with: [link to minified js](https://raw.githubusercontent.com/mebjas/html5-qrcode/beta-zxing/minified/html5-qrcode.min.js)

Please let me know if this addresses your usecase.

**Comment by mebjas** [comment] 2020-11-22 13:33
Also, @ianbroad This issue is a duplicate of https://github.com/mebjas/html5-qrcode/issues/61. I am closing this one, please follow #61 for more details on this.

**Closed** 2020-11-22 13:33 UTC
