### ISSUE TITLE
Error locator degree does not match number of roots

### ISSUE THREAD

**Issue by syfgkjasdkn** [mebjas/html5-qrcode#55] opened 2020-06-08 20:48 UTC
I'm getting `QR code parse error, error = Error locator degree does not match number of roots` error when parsing 

![download](https://user-images.githubusercontent.com/43219386/84081821-5d88b000-a9e7-11ea-8c51-c7412d37de73.png)

as a file. 

`zbar` however works fine:

```
> zbarimg ~/Downloads/download.png
QR-Code:http://localhost:4000/sensors/f1eb00a6-7e84-426a-9fd5-01ab709349b3
scanned 1 barcode symbols from 1 images in 0.03 seconds
```

**Comment by mebjas** [comment] 2020-06-10 01:40
I see what you are saying - I was able to reproduce this. The problem is coming from downscaling the qrcode too much before scanning it.

As I increased the canvas size I was able to scan the same code - I'll send a fix for this

![image](https://user-images.githubusercontent.com/3007365/84217314-6fa94200-aafe-11ea-8548-8b72b3b880e8.png)

**Comment by mebjas** [comment] 2020-06-13 06:57
Sent a push which is now able to scan these new codes - https://github.com/mebjas/html5-qrcode/commit/97a3c10373fb72b9eab29f6a9f77898b6fd5f2fc

Please feel free to close this issue once you have verified, assigning it to you.

Latest changes published to
 - npm - https://www.npmjs.com/package/html5-qrcode 
 - https://github.com/mebjas/html5-qrcode/releases/tag/V1.1.2
 - https://blog.minhazav.dev/research/html5-qrcode

**Comment by syfgkjasdkn** [comment] 2020-06-13 17:45
@mebjas thank you!

**Closed** 2020-06-13 17:45 UTC
Labels: bug, verification-needed
