### ISSUE TITLE
V1.2.3 failed to work in ios devices

### ISSUE THREAD

**Issue by mahasadhu** [mebjas/html5-qrcode#136] opened 2020-11-13 09:54 UTC
**Describe the bug**
I just tried using this library v1.2.3 , but it does not show any camera on ios devices. The demo page (https://blog.minhazav.dev/research/html5-qrcode.html) also is not working.

Happened on iOS using safari browser. Cannot see the console for any errors because it's a phone.

**To Reproduce**
1. Try to scan using ios / iphone devices using safari and library v1.2.3
2. No camera or anything shown

**Expected behavior**
Scan and camera works as usual

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - Browser: safari

**Additional context**
N/A

**Comment by Eschon** [comment] 2020-11-13 10:50
I also ran into that issue. The Problem seems to be that iOS Safari does not support the used JavaScript syntax yet. Since the class Syntax should be supported it is probably the static properties. Here are the errors that I get:
<img width="990" alt="Screenshot 2020-11-13 at 11 47 02" src="https://user-images.githubusercontent.com/11647830/99064526-596c4a00-25a6-11eb-8a3f-4f94e611e5e2.png">

**Comment by mebjas** [comment] 2020-11-23 05:03
Thanks for pointing this out, there was a recent regression in demo code, which broke it for Safari IOS. This has been fixed now please retry

**Comment by mebjas** [comment] 2020-11-23 05:04
I have tested latest demo on iphone 7 safari and it works now.

**Comment by mahasadhu** [comment] 2020-11-26 06:14
@mebjas could you tell me what's changed? because I don't see any new release or new commit pushed to the repo. Or am I missing something?

And yes it's working on our iphones here too on safari

Thanks!

**Comment by mebjas** [comment] 2020-12-06 08:15
It was a wrong deployment of code to the demo page, it wasn't an issue in published library.

**Comment by mebjas** [comment] 2020-12-06 08:15
Marking as closed for now, thanks for verification.

**Closed by mebjas** 2020-12-06 08:15 UTC
Labels: Priority1, verification-needed

**Comment by mahasadhu** [comment] 2020-12-07 04:39
umm, when I was first found this issue, I found it by using the published library (v1.2.3). 

I only tried the demo page after I realized it's not working on our devices, to make sure whether the problem was only on us or in the actual library itself.
