### ISSUE TITLE
Compatibility - [MacOS/iOS] [Firefox/Safari] - [UPC Scanning]

### ISSUE THREAD

**Issue by connorpwilliams** [mebjas/html5-qrcode#341] opened 2021-10-31 22:08 UTC
**Describe the bug**
UPCs do not seem to be scanning with browser.
I have tried both MacOS + Firefox and iPhone 11 + Safari. In both cases, qrcode scanning is successful but barcode scanning is not.

**NPM Package**
`"html5-qrcode": "^2.1.0"`

**Describe the browser:**
- MacBook Pro '19
 - OS: [MacOS Monteray]
 - Browser [Firefox]
 - Version [Latest]
AND
- iPhone 11 Pro Max
 - OS: [iOS 15.1]
 - Browser [Safari]
 - Version [Latest]

**Screenshots**
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/7041672/139602721-42d927b9-6258-46ae-a826-0d4464ef227d.png">

**Additional context**
Here is what I'm doing to create a new instance.
```js

    componentDidMount() {
        let scanner = new Html5QrcodeScanner("reader", {
            fps: 15,
            qrbox: { width: 300, height: 250 },
            experimentalFeatures: {
                useBarCodeDetectorIfSupported: true
            }
        });
        scanner.render(this.scanSucces, this.scanError)
    }
```

**Comment by mebjas** [comment] 2021-11-01 11:57
seems to get scanned on my Pixel device - decodes to `036000291452`. I wonder if this has to do with the grid background on the UPC code - can you try it with white background?

**Comment by thecpdubguy** [comment] 2021-11-01 15:17
![image](https://user-images.githubusercontent.com/7041672/139695275-8761c36c-a102-43b8-98cf-a4214bb94962.png)

This doesn't seem to work iPhone 11, iOS 15.1, Firefox or Safari

**Comment by thecpdubguy** [comment] 2021-11-01 15:19
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/7041672/139695618-59793757-e31f-4a17-bd85-1eecaeca08fe.png">

Or this on MacOS Monterey + Firefox

**Comment by runtim** [comment] 2022-02-15 02:06
Confirmed what appears to be the same issue on iOS 15.1 and 15.3.1 (multiple phones) Safari and Chrome.  I am unable to scan any barcodes.  No issue with QR codes.

**Comment by mebjas** [comment] 2022-10-30 05:26
Duplicate of https://github.com/mebjas/html5-qrcode/issues/323 -- please track there.

**Closed by mebjas** 2022-10-30 05:26 UTC
Labels: compatibility
