### ISSUE TITLE
htmlentity &nbsp; visible in IOS safari 14.6

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [mebjas/html5-qrcode#240] opened 2021-06-20 18:14 UTC
between "select camera(X0&nbsp;<select.....>
the &nbsp; is not considered as an html entity. Not visible in Android, Windows, Linux

**Comment by mebjas** [comment] 2021-06-21 13:20
yeah this was just fixed in `v2.0.11` - could you verify?

**Comment by ROBERT-MCDOWELL** [comment] 2021-06-21 13:45
still the same :(

**Comment by ROBERT-MCDOWELL** [comment] 2021-06-22 13:36
apparently it appears only on Safari and Firefox.
chrome and chrome like + edge are ok

**Comment by mebjas** [comment] 2021-06-27 08:05
For some reason I cannot reproduce this on iOS 13.0, Safari.
Cannot reproduce this on Chrome / Safari on Mac either.

This was recently fixed, maybe some cache issue? Can you try again.

**Comment by ROBERT-MCDOWELL** [comment] 2021-06-27 12:06
My tests are on iOS 14.6
Chrome is ok,  the issue is just on Safari and Firefox.
I'm always working my dev with browser cache disabled.

**Comment by mebjas** [comment] 2021-09-17 19:52
@ROBERT-MCDOWELL is this still an isse?

**Comment by ROBERT-MCDOWELL** [comment] 2021-09-17 21:47
It's fixed, great  job for the last version!

**Closed** 2021-09-17 21:47 UTC
Labels: Priority1
