### ISSUE TITLE
UPC isn’t detected

### ISSUE THREAD

**Issue by Leonick** [mebjas/html5-qrcode#323] opened 2021-10-16 12:41 UTC
**Describe the bug**
UPC-A and UPC-E codes doesn't seem to be detected even when configured to

I've tried both my own implementation of Html5Qrcode and with you example page. Tried your example UPC pictures, several codes on actual product boxes, and picture from Google search. None are detected.

Other barcodes such as EAN work.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone Mini 12 and iPhone 7
 - OS: iOS 15 and iOS 14
 - Browser: Safari

**Additional context**
![image](https://user-images.githubusercontent.com/2903631/137587801-e55703bf-ef15-4280-8c31-ee8519eebd50.jpeg)
![image](https://user-images.githubusercontent.com/2903631/137587808-23284dbb-0c2a-41fe-884d-b2771a2230bb.jpeg)
![image](https://user-images.githubusercontent.com/2903631/137587813-bfe41ded-2754-4ec3-81a5-714e33e5448b.jpeg)

**Comment by vishakha-simply** [comment] 2021-11-04 18:03
@Leonick hey did you find any solution to this ?
I'm struggling with the same

**Comment by Leonick** [comment] 2021-11-06 07:52
@vishakha-simply 
I did not. Had to use a different solution. github.com/ericblade/quagga2
Examples are out of date and documentation not as good so bit trickier to set up, but it works.

**Comment by ROBERT-MCDOWELL** [comment] 2021-11-06 12:09
why not to grab the quagga2 code that works with UPC code an integrte it in html5-qrcode?

**Comment by marcinheniborg** [comment] 2022-03-21 12:57
Hey @mebjas,
awesome job with this repo. Thanks! I'm really excited to use it with the inventory app that I'm developing based on the Google App Script. However I'm experiencing the same issues as other commenters. The app is not scanning codes from the popular items which are with UPC codes. Do you foresee looking into this anytime soon? 
Thank you!

**Comment by erikmillergalow** [comment] 2022-04-05 22:16
@mebjas Do you have a sense of whether or not a fix for iOS barcode scanning will make it into any releases in the near future? I'm evaluating this package to replace quagga, the speed and accuracy is great but I need to support both Android and iOS.

**Comment by gbsystems** [comment] 2022-04-12 11:05
2.2.1 Not scanning for me in FF+Chrome on Android
+1 for rectification of this bug, spoiling an otherwise excellent piece of software

**Comment by mebjas** [comment] 2022-10-30 05:26
Will look into this based on @Breno1288 's PR.

**Comment by mebjas** [comment] 2022-11-16 15:30
Fixed in zxing-js. Will be published in `version 2.3.1`. Now UPC-A and UPC-E will get scanned without `useBarCodeDetectorIfSupported` support - thus across platform.

Track progress on this version at: https://github.com/mebjas/html5-qrcode/issues/605

**Comment by mebjas** [comment] 2022-11-16 16:02
Issue fixed with version 2.3.1 -- please help with verification (please comment in issue #605 if the issue is still reproduced in certain platform).

Github release: https://github.com/mebjas/html5-qrcode/releases/tag/v2.3.1
NPM: https://www.npmjs.com/package/html5-qrcode/v/2.3.1

Closing this issue for now.

**Closed by mebjas** 2022-11-16 16:02 UTC
Labels: Priority1
