### ISSUE TITLE
why this qrcode no detected

### ISSUE THREAD

**Issue by nivthetool** [mebjas/html5-qrcode#451] opened 2022-03-24 11:01 UTC
any idea why this qrcode not detected by your demo app and my js html_qrcode
and it is detected by my phone camera
getting error "No MultiFormat Readers were able to detect the code.
![chen-tree-barcode](https://user-images.githubusercontent.com/13106481/159902664-5b093316-5711-4bee-813f-00f2c1443a14.jpg)
"

**Comment by ROBERT-MCDOWELL** [comment] 2022-03-24 12:09
i'ts a negative qrcode, not yet supported.
duplicate of https://github.com/mebjas/html5-qrcode/issues/94
please close the issue thanks.

**Comment by nivthetool** [comment] 2022-03-24 13:09
10x any alternatives/workarounds you are aware of
TIA

**Comment by mebjas** [comment] 2022-11-17 15:11
duplicate - will share more updates on parent issue directly, please track #94

**Closed by mebjas** 2022-11-17 15:11 UTC
