### ISSUE TITLE
Language / Text props support

### ISSUE THREAD

**Issue by Mario8419** [mebjas/html5-qrcode#556] opened 2022-10-17 05:32 UTC
Really nice library, but is it possible to change text for internationality and functionality like to allow scan an image file or not and button styling? This would be really nice. thank you

**Comment by mebjas** [comment] 2022-11-17 14:33
Duplicate of https://github.com/mebjas/html5-qrcode/issues/132

Please track the issue there (it’s on my radar). Would you be interested in helping with the translation for certain languages?

**Closed by mebjas** 2022-11-17 14:33 UTC
Labels: enhancement, ferature-request, Priority1
