### ISSUE TITLE
Scanning same QR code not firing success function

### ISSUE THREAD

**Issue by ShankaranarayananB** [mebjas/html5-qrcode#701] opened 2023-02-15 08:43 UTC
I'm implementing ticket scanning app where I need to check-in / checkout users based on QR code . When I try to scan same QR code its not firing success function.

**Comment by coderbyheart** [comment] 2023-02-15 10:13
Duplicate of https://github.com/mebjas/html5-qrcode/issues/699

**Closed** 2023-02-17 04:46 UTC
