### ISSUE TITLE
y: No MultiFormat Readers were able to detect the code

### ISSUE THREAD

**Issue by stasvoler** [mebjas/html5-qrcode#503] opened 2022-07-11 08:22 UTC
**Describe the bug**
I tested the demo app and found that an error occurs when uploading image files with long CODE128 barcodes.

**_"y: No MultiFormat Readers were able to detect the code."_**

**Screenshots**
![Issue1](https://user-images.githubusercontent.com/5755140/178220321-3e46d5f6-643f-4dae-9b27-2a923e9b114a.png)
![Issue2](https://user-images.githubusercontent.com/5755140/178220336-c15622ef-d5a3-4c68-afd5-76764cea9e02.png)
![Issue3](https://user-images.githubusercontent.com/5755140/178220348-f502da3b-0f7d-44d2-8f59-54398ad46e9a.png)
![Issue4](https://user-images.githubusercontent.com/5755140/178220361-f4eac44c-ca51-4231-93ee-1d525f015c9e.png)

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 102.0.1

**Comment by ROBERT-MCDOWELL** [comment] 2022-07-11 10:53
you need to have a consequent white margin around the barcode....

**Comment by ROBERT-MCDOWELL** [comment] 2022-07-15 10:18
dunno, maybe you are better to buy a scanner software without this limitation

**Comment by stasvoler** [comment] 2022-07-15 11:30
I tried scanning these codes with zxing-js  library (https://github.com/zxing-js/library) and it works without any problems.

**Comment by mebjas** [comment] 2022-11-17 14:58
I think I know the root cause of this. It would be great if the authors or other could share the original images used for testing. Further more this issue shall now be tracked in a parent bug - https://github.com/mebjas/html5-qrcode/issues/612

Closing this one.

Please feel free to reply directly in the parent issue.

**Closed by mebjas** 2022-11-17 14:58 UTC
