### ISSUE TITLE
Compatibility - [html5QrcodeScanner cant able to stop programatically]

### ISSUE THREAD

**Issue by rohanashik** [mebjas/html5-qrcode#72] opened 2020-06-28 13:16 UTC
html5QrcodeScanner cant able to stop programatically, I want to stop the camera after a successful scan code.
In Html5Qrcode there is stop action. But I want in html5QrcodeScanner

**Comment by mebjas** [comment] 2020-06-30 01:07
This is a good requirement, I didn't realize the end to end solution would also need APIs, I'll add this.

Thanks for posting.

**Comment by mebjas** [comment] 2020-07-05 12:43
@rohanashik Sorry I missed this `Html5QrcodeScanner` already supports `clear()` method which takes care of closing the scanning and clearing up the user interface. Can you use that for your use-case?

I have updated it to return `Promise` so that its more reliable to caller.

You can stop like this:

```js
let html5QrcodeScanner = new Html5QrcodeScanner(
	"reader", { fps: 10, qrbox: 250 }, /* verbose= */ true);

function onScanSuccess(qrMessage) {
  // handle the scanned code as you like
  console.log(`QR matched = ${qrMessage}`);
  // Stop scanning
  html5QrcodeScanner.clear().then(_ => {
    // the UI should be cleared here      
  }).catch(error => {
    // Could not stop scanning for reasons specified in `error`.
    // This conditions should ideally not happen.
  });
}

function onScanFailure(error) {
  // handle scan failure, usually better to ignore and keep scanning
  console.warn(`QR error = ${error}`);
}

html5QrcodeScanner.render(onScanSuccess, onScanFailure);
```

**Comment by yerayb** [comment] 2020-07-09 09:48
Hi. How can I stop the qr scanner? Currently, my code is like this. 
` // LECTOR QR
                                            var lastResult, countResults = 0;
                                            function onScanSuccess(qrCodeMessage) {
                                                if (qrCodeMessage !== lastResult) {
                                                    ++countResults;
                                                    lastResult = qrCodeMessage;
                                                    angular.element($('[ng-controller="NewShoppingListController"]')).scope().addItem(); //llama a la funcion de angular AddItem desde JS - Agregar en BD

                                                }
                                            }
                                            var html5QrcodeScanner = new Html5QrcodeScanner(
                                                "qr-reader", { fps: 10, qrbox: 250 });
                                            html5QrcodeScanner.render(onScanSuccess);`
Once the addItem method has been run, I want it to stop scanning. I have tried the clear method in several ways but without success. Thank you.

**Comment by yerayb** [comment] 2020-07-09 09:48
Hi. How can I stop the qr scanner? Currently, my code is like this. 
```
` // LECTOR QR
                                            var lastResult, countResults = 0;
                                            function onScanSuccess(qrCodeMessage) {
                                                if (qrCodeMessage !== lastResult) {
                                                    ++countResults;
                                                    lastResult = qrCodeMessage;
                                                    angular.element($('[ng-controller="NewShoppingListController"]')).scope().addItem(); //llama a la funcion de angular AddItem desde JS - Agregar en BD

                                                }
                                            }
                                            var html5QrcodeScanner = new Html5QrcodeScanner(
                                                "qr-reader", { fps: 10, qrbox: 250 });
                                            html5QrcodeScanner.render(onScanSuccess);`
```
Once the addItem method has been run, I want it to stop scanning. I have tried the clear method in several ways but without success. Thank you.

**Comment by mebjas** [comment] 2020-07-09 12:10
@yerayb small modification 
```js
var html5QrcodeScanner = new Html5QrcodeScanner(
	"qr-reader", { fps: 10, qrbox: 250 });
var lastResult, countResults = 0;
function onScanSuccess(qrCodeMessage) {
	if (qrCodeMessage !== lastResult) {
		++countResults;
		lastResult = qrCodeMessage;
		angular.element($('[ng-controller="NewShoppingListController"]')).scope().addItem();
		html5QrcodeScanner.clear();
	}
}
html5QrcodeScanner.render(onScanSuccess);
```

Can you try this?

**Comment by yerayb** [comment] 2020-07-09 13:25
I try this. The scanner continues to run but does not stop.

**Comment by mebjas** [comment] 2020-07-19 06:05
Hi @yerayb  please try the latest version `v1.1.8` I made some bug fixes and have validated it to work - example: https://blog.minhazav.dev/research/scan

**Comment by yerayb** [comment] 2020-07-19 21:45
Thanks!!! Now the clear method works correctly. To other cases,  is there any way to stop the scanner without it disappearing?  Thanks for everything!!

**Closed** 2020-07-20 03:38 UTC
Labels: bug, enhancement

**Comment by fgirolami29** [comment] 2020-07-20 13:41
thanks a lot , 

solution 100% work

docReady(function () {
        var resultContainer = document.getElementById('qr-reader-results');
        var lastResult, countResults = 0;
        function onScanSuccess(qrCodeMessage) {
             
            if (qrCodeMessage !== lastResult) {
                ++countResults;
                lastResult = qrCodeMessage;
                resultContainer.innerHTML
                    += `${qrCodeMessage}`;
                **html5QrcodeScanner.clear();**
            }
        }

**Comment by dseeker** [comment] 2021-03-07 15:07
If the scanner is running .clear() works perfectly, but before pressing the start scanning the clear method has no effect. How to close the UI the same way as clear without having started scanning first?

**Comment by picocodes** [comment] 2021-09-13 09:14
@mebjas if you could add class names to the start scanning and stop scanning buttons, it would make things easier. We can just trigger a fake click on those.

**Comment by mohamadmohseni7913** [comment] 2023-07-23 06:51
hi 
how can can I stop the scanner after change route 
i don't want use camera in all route 
and when scanner start and route changed camera is using

**Comment by vipansh** [comment] 2024-01-11 18:27
import { Html5Qrcode } from "html5-qrcode";
import { ChangeEvent, useEffect, useRef, useState } from "react";

// assuming this is the correct path

type QrScannerConfig = {
  fps: number;
  qrbox: { width: number; height: number };
  aspectRatio: number;
};

type QrScannerErrorCallback = (errorMessage: string) => void;
type QrScannerSuccessCallback = (decodedText: string, result?: any) => void;

const useQrScanner = (
  config: QrScannerConfig,
  qrCodeSuccessCallback: QrScannerSuccessCallback,
  qrCodeErrorCallback?: QrScannerErrorCallback
) => {
  const [error, setError] = useState<string | null>(null);
  const previewRef = useRef<HTMLDivElement>(null);
  const html5QrCodeRef = useRef<Html5Qrcode | null>(null);

  useEffect(() => {
    if (!previewRef.current) return;

    html5QrCodeRef.current = new Html5Qrcode(previewRef.current.id);
    const html5QrCode = html5QrCodeRef.current;

    html5QrCode
      .start(
        { facingMode: "environment" },
        config,
        qrCodeSuccessCallback,
        (errorMessage: string) => {
          qrCodeErrorCallback?.(errorMessage);
          // setError(errorMessage);
        }
      )
      .catch((error) => {
        console.error("QR Scanner initialization failed:", error);
        setError(error.message);
      });

    return () => {
      if (html5QrCode.isScanning) {
        html5QrCode
          .stop()
          .then(() => {
            console.log("Scanner stopped successfully");
            html5QrCode.clear();
          })
          .catch((error) => {
            console.error("Error stopping scanner:", error);
          });
      } else {
        html5QrCode.clear();
      }
    };
  }, [config, qrCodeErrorCallback, qrCodeSuccessCallback]);

  const handleFileUpload = async (e: ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!previewRef.current || !files || !html5QrCodeRef.current) return;

    const html5QrCode = html5QrCodeRef.current;

    try {
      const decodedText = await html5QrCode.scanFile(files[0], true);
      console.log({ decodedText });
      qrCodeSuccessCallback(decodedText);
    } catch (err) {
      console.error(`Error scanning file. Reason: ${err}`);
      setError(`Error scanning file. Reason: ${err}`);
    } finally {
      setTimeout(async () => {
        html5QrCode.clear();
        try {
          await html5QrCode.start(
            { facingMode: "environment" },
            config,
            qrCodeSuccessCallback,
            (errorMessage: string) => {
              console.error(
                `Error during re-starting scanner. Reason: ${errorMessage}`
              );
            }
          );
        } catch (err) {
          console.error(`Error restarting scanner. Reason: ${err}`);
        }
      }, 1000);
    }
  };

  return { previewRef, handleFileUpload, error };
};

export default useQrScanner;


camera is not stopping on Unmount

**Comment by svillacreses** [comment] 2025-02-26 20:05
I tried using the 'clear()' method to close it but I get an error message saying "Cannot clear while scan is ongoing, close it first."

Also tried pausing it first and clearing it after but no luck (the issue is happening on my android mobile using chrome, in my macbook is working great)

**Comment by risalfajar** [comment] 2025-05-17 23:03
@svillacreses have you found the solution? That also happened on mine

**Comment by ROBERT-MCDOWELL** [comment] 2025-05-18 10:47
just delete the object.
