### ISSUE TITLE
Camera doesn't show up in webview inside mobile app

### ISSUE THREAD

**Issue by shain-digix** [mebjas/html5-qrcode#130] opened 2020-10-20 09:45 UTC
**Describe the bug**
I was trying to use the plugin in a webpage to be shown as webview inside an app. For web browsers, it works good. But in the app webview, the camera doesn't show. Any suggestions to fix this?

**Comment by mebjas** [comment] 2020-10-25 09:20
This is duplicate of https://github.com/mebjas/html5-qrcode/issues/58. I tried to fix this before but couldn't get to the root cause. I'll try to spend more time to see if this support can be extended. Please track this issue in the #58 , if you feel it's different, please feel free to reopen this issue.

**Closed by mebjas** 2020-10-25 09:20 UTC
