### ISSUE TITLE
Barcode Isn't detected, Demo Page Works fine

### ISSUE THREAD

**Issue by Read1337** [mebjas/html5-qrcode#531] opened 2022-08-22 17:22 UTC
Hey,
The example on this page works. https://blog.minhazav.dev/research/html5-qrcode.html 
When I follow the example to include my own project, nothing happens. The camera is loaded but no barcode or Qr Code is detected.

This is my code from the example

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test</title>
    <script src="https://unpkg.com/html5-qrcode"></script>
  </head>
  <body>
    <div id="qr-reader" style="width: 600px"></div>
    <script>
        function onScanSuccess(decodedText, decodedResult) {
            console.log(`Code scanned = ${decodedText}`, decodedResult);
       }
       var html5QrcodeScanner = new Html5QrcodeScanner(
         "qr-reader", { fps: 10, qrbox: 250 });
       html5QrcodeScanner.render(onScanSuccess);
    </script>
  </body>
</html>
```

I was expecting this sample code to work and go from there.

I'm using macOS Monterey v12.5
Google Chrome Version 104.0.5112.101

Doesn't work on my local development or production with https
I also tried in Safari browser on macOS and iPhone 12

Again, The example page works fine.

**Comment by Geminite** [comment] 2022-08-27 08:36
Did you manage to fix this problem? I also have the same issue where I can scan a QR code but the result is not shown.

**Comment by motud2** [comment] 2022-09-20 08:00
Same issue, iPad, iOS 15.6.1

**Comment by vincentckk** [comment] 2022-11-01 04:03
Did any result displayed in the console.log?

**Comment by mebjas** [comment] 2022-11-01 14:20
Likely due to this additional config in demo

```ts
experimentalFeatures: {
    useBarCodeDetectorIfSupported: true
},
```

Try changing to 

```js
var html5QrcodeScanner = new Html5QrcodeScanner(
         "qr-reader", { fps: 10, qrbox: 250 , experimentalFeatures: {useBarCodeDetectorIfSupported: true}});

html5QrcodeScanner.render(onScanSuccess);
```

**Comment by mebjas** [comment] 2022-11-17 14:42
if this is about UPC-A or UPC-E codes, the issues are fixed with v2.3.2 please retry.

Closing this issue for now, please reopen if the issue is still observed.

**Closed by mebjas** 2022-11-17 14:42 UTC

**Comment by m81147155-boop** [comment] 2026-06-26 22:03
https://ikperfume.webimaker.com/

**Comment by m81147155-boop** [comment] 2026-06-26 22:04
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>QR Code Scanner</title>

  <script src="https://unpkg.com/html5-qrcode"></script>

  <style>
    body{
      font-family: Arial, sans-serif;
      text-align:center;
      background:#f4f4f4;
      padding:20px;
    }
    #reader{
      width:300px;
      margin:auto;
    }
    #result{
      margin-top:20px;
      font-size:18px;
      color:green;
      word-break: break-word;
    }
  </style>
</head>
<body>

<h2>QR Code Scanner</h2>

<div id="reader"></div>

<div id="result">Scan a QR Code...</div>

<script>
function onScanSuccess(decodedText) {
    document.getElementById("result").innerHTML =
      "<b>Result:</b> " + decodedText;
}

new Html5QrcodeScanner(
    "reader",
    { fps: 10, qrbox: 250 }
).render(onScanSuccess);
</script>

</body>
</html>
