### ISSUE TITLE
[Feature Request] Could you please add CSS classes to the buttons

### ISSUE THREAD

**Issue by picocodes** [mebjas/html5-qrcode#447] opened 2022-03-21 08:10 UTC
Specifically the Close Button.

**Comment by ROBERT-MCDOWELL** [comment] 2022-06-11 13:12
you can contribute to it thanks

**Comment by mebjas** [comment] 2022-10-29 15:58
Good idea, will be tracked at https://github.com/mebjas/html5-qrcode/issues/389

Marking this as a duplicate of https://github.com/mebjas/html5-qrcode/issues/389

Let's have more discussion there.

**Closed by mebjas** 2022-10-29 15:58 UTC
Labels: enhancement, ferature-request
