### ISSUE TITLE
When mobile camera focus is not working. Not detect qrcode

### ISSUE THREAD

**Issue by Hateeb** [mebjas/html5-qrcode#465] opened 2022-04-19 05:32 UTC
I have use your library in WordPress plugin PWA interface. But when camera is high definition it focus is not detect qrcode.
Kindly suggestion me solution what can I do this.

**Comment by mebjas** [comment] 2022-11-17 15:05
Duplicate of https://github.com/mebjas/html5-qrcode/issues/464 - please track directly

**Closed by mebjas** 2022-11-17 15:05 UTC
