### ISSUE TITLE
[Feature Request] Responsive video and canvas

### ISSUE THREAD

**Issue by Evaldash** [mebjas/html5-qrcode#439] opened 2022-03-10 15:42 UTC
**Is your feature request related to a problem? Please describe.**
It's a bit of an annoyance: Once the scanner is initialized, it isn't responsive. When you resize the window, the scanner stays the same size. If I make the camera responsive, the QR code scanning breaks.

**Describe the solution you'd like**
I'd like if the scanner and canvas were responsive, that is changed size, or the canvas reacted to the size of the video atleast, according to the viewport.

**Describe alternatives you've considered**
I used to use this repo instead: https://github.com/nimiq/qr-scanner
Sadly, it doesn't support all of the browsers I need. When the video changed size, the canvas's size changed accordingly.

**Comment by mebjas** [comment] 2022-11-17 15:17
duplicate of #441 - please track here directly.

**Closed by mebjas** 2022-11-17 15:17 UTC
Labels: enhancement, ferature-request
