### ISSUE TITLE
Lots of logs even when verbose is false

### ISSUE THREAD

**Issue by JimmyBjorklund** [mebjas/html5-qrcode#175] opened 2021-04-15 07:31 UTC
Lots of logs even when verbose is false

N
    at Jt.decodeRow2pairs (http://localhost:4200/scripts.js:1:109332)
    at Jt.decodeRow (http://localhost:4200/scripts.js:1:108988)
    at ee.decodeRow (http://localhost:4200/scripts.js:1:124433)
    at ee.doDecode (http://localhost:4200/scripts.js:1:64409)
    at ee.decode (http://localhost:4200/scripts.js:1:63485)
    at ir.decodeInternal (http://localhost:4200/scripts.js:1:252784)
    at ir.decode (http://localhost:4200/scripts.js:1:251787)
    at p (http://localhost:4200/scripts.js:1:294228)
    at b (http://localhost:4200/scripts.js:1:294786)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:412:35)

**Comment by linusnorton** [comment] 2021-04-15 07:46
I came here to say the same. It's killing firefox

**Comment by mebjas** [comment] 2021-04-15 12:43
Ah looks like a regression from a recent pull request. Working on addressing this.

**Comment by mebjas** [comment] 2021-04-15 14:18
The fix is submitted and released as version 2.0.1 please take a look.

 - Github release - https://github.com/mebjas/html5-qrcode/releases/tag/V2.0.1
 - NPM - https://www.npmjs.com/package/html5-qrcode

**Comment by mebjas** [comment] 2021-04-15 14:19
@linusnorton @JimmyBjorklund Could you help verify the fix?

**Comment by linusnorton** [comment] 2021-04-15 14:41
@mebjas confirmed fixed

**Closed** 2021-04-15 15:08 UTC
Labels: Priority1, fix-submitted, verification-needed

**Comment by JimmyBjorklund** [comment] 2021-04-15 16:31
Works
