### ISSUE TITLE
[Feature Request] qrcode language Support

### ISSUE THREAD

**Issue by khaledway** [mebjas/html5-qrcode#379] opened 2021-12-29 10:59 UTC
Hello! I am using the scanner and I have to say, it's amazing! One question, is it possible to change the language to "Arabic"? 
I wanted to change the text like idle, or "Request Camera Permissions" to another language. Is that possible?

**Comment by AnasSafi** [comment] 2022-09-12 06:15
You can do that: 

```

            let html5QrcodeScanner = new Html5QrcodeScanner(
                "reader",
                { fps: 10, qrbox: {width: 250, height: 250} },
                /* verbose= */ false);
            html5QrcodeScanner.render(onScanSuccess, onScanFailure);
            $("button#reader__camera_permission_button").html('طلب صلاحية الكاميرا');
            $("a#reader__dashboard_section_swaplink").html('الحصول على الباركود من صورة');
```

**Comment by mebjas** [comment] 2022-11-17 14:35
Working on internationalisation.

Duplicate of https://github.com/mebjas/html5-qrcode/issues/132. Please track this parent bug directly.

**Closed by mebjas** 2022-11-17 14:35 UTC
Labels: enhancement, ferature-request
