### ISSUE TITLE
[Feature Request] One liner for the request

### ISSUE THREAD

**Issue by Hussein010** [mebjas/html5-qrcode#525] opened 2022-08-16 06:49 UTC
Is there a feature when on mobile to only show the rear camra in the options ?

**Comment by mebjas** [comment] 2022-11-17 14:43
have you tried using `facingMode`: `environment`?

https://github.com/mebjas/html5-qrcode#scanning-without-cameraid

**Comment by mebjas** [comment] 2022-11-17 14:44
Please reopen if the issue is not resolved, closing for now.

Also, please set the issue title correctly for more reference.

**Closed by mebjas** 2022-11-17 14:44 UTC
Labels: enhancement, ferature-request
