### ISSUE TITLE
Same QR code scan gives different results

### ISSUE THREAD

**Issue by aminurrashid** [mebjas/html5-qrcode#63] opened 2020-06-16 03:50 UTC
**Describe the bug**
When scanning, same QR code different results. Though it's random but very frequent.

Sample QR code:
![sample qr](https://user-images.githubusercontent.com/4655668/84728511-3ca9f700-afb3-11ea-9ac3-e7569aad1488.png)

Scan results:
![Screenshot_20200616-092601](https://user-images.githubusercontent.com/4655668/84728765-d5407700-afb3-11ea-9b45-755c2501cc07.png)

Expected result: {"bp_id":"eb1faf1fa48e1801","pt_id":"d78f8bbd036be151"}

As you can see following results are not correct:
2nd result: pv_id instead of pt_id
4th result: "bp_id":2eb1... instead of "bp_id":"eb1
6th result: "bp_id":"...1841" instead of "bp_id":"...1801"
8th result: "br_id" instead of "bp_id"

**To Reproduce**
1. Go to https://blog.minhazav.dev/research/html5-qrcode.html
2. Scan the given QR code.

**Expected behavior**
Scan result should always show: {"bp_id":"eb1faf1fa48e1801","pt_id":"d78f8bbd036be151"}

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.97

**Smartphone (please complete the following information):**
 - Device: Nexus 6P
 - OS: android 8.1.0
 - Browser: Chrome
 - Version: 83.0.4103.96

**Comment by mebjas** [comment] 2020-06-21 12:03
@aminurrashid Thanks for posting this, this is similar to https://github.com/mebjas/html5-qrcode/issues/60 and for starters I'd recommend if you could try the same solution here.

Meanwhile I'd try to see if the result could be more deterministic. This seems off behavior by the underlying `qrcode` scanning library.

**Comment by max2ti** [comment] 2020-08-06 09:47
I noticed the same problem, I generated a qr containing `qwertyuiopasdfghjklzxcvbnm,.-è+ò`, printed it and took a bunch of pictures of it (different lights, distance, focus...).

First thing I noticed, special characters like "è" or "ò" are not decoded well: `qwertyuiopasdfghjklzxcvbnm,.-Ã¨+Ã²` but that can be fixed by applying a proper utf8 encoding (see this old post http://ecmanaut.blogspot.com/2006/07/encoding-decoding-utf8-in-javascript.html).

The real problem is that 2 out of 28 pictures decoded to the wrong strings:

```
original: qwertyuiopasdfghjklzxcvbnm,.-è+ò
error1:   qwertyuiopasdfg`jklzxcvbnm,.-è+ò
                         ^
error2:   qwertyuiopasdfghjklzxcVbnm,.-è+ò
                                ^
```

Depending on the application this could really be a big problem, most of the times you have no way to tell if the code is wrong. The problem is most likely in the underlying library https://github.com/LazarSoft/jsqrcode which is abandoned. Do you use it directly or do you maintain a custom version of it?

**Comment by mebjas** [comment] 2020-08-09 07:16
Yes you are right, I have seen this issue in a flaky fashion and this is a reliability issue which can be problematic for some applications.

> can be fixed by applying a proper utf8 encoding (see this old post http://ecmanaut.blogspot.com/2006/07/encoding-decoding-utf8-in-javascript.html).

Thanks for this, I'll take a look.

> The problem is most likely in the underlying library https://github.com/LazarSoft/jsqrcode which is abandoned. Do you use it directly or do you maintain a custom version of it?

I have started to maintain a new this myself now at [third_party/qrcode.js](https://github.com/mebjas/html5-qrcode/blob/master/third_party/qrcode.js). However the library is very big and I need to build more expertise on that to be able to fix this. But this is annoying and can render the library useless for some applications - hence I'd like to priortise this.

I was thinking of some temporal filtering on app side as well to give more reliable results but that can increase scan latency and performance.

**Comment by jesusrodriguezm** [comment] 2020-08-19 14:31
Same problem here, in my case using the library in a web app. I have a QR Code that contains an URL, and sometimes it changes a letter (breaking the URL).

**Comment by max2ti** [comment] 2020-08-19 14:42
A way to approach this problem could be experimenting with the 4 error correction levels (https://www.qrcode.com/en/about/error_correction.html). It would be interesting to generate a QR for the same data with each error correction level (so 4 QR) and then try to see if this library failures rate is influenced by the level or not. If it isn't it might mean that the underlying algorithm doesn't implement error correction at all. It might be the best outcome, at least you would know what to do to fix it, rather than hunting a nasty random bug.

**Comment by ygoe** [comment] 2020-10-09 15:17
I also see decoding errors. The text often contains the same errors, single characters are wrong. Sometimes, lots of unprintable garbage is appended to the decoded text. I tried on my desktop USB webcam (720p) in Firefox with a QR code shown by a QR generator on my smartphone.

There's nothing I can do on the application side to detect this. I want to decode 1) short device IDs without any checksum and 2) an OTP export QR code that I cannot verify myself. I have to rely on the error detection (and correction if possible) of the decoding library.

The question is, why doesn't the QR decoder even detect this error and gives me invalid data? There's FEC data in the code, so I assume there's also a way to detect errors. What's happening here?

**Comment by mebjas** [comment] 2020-11-22 13:28
Folks thanks for the patience, this issue was priority1 and I have been trying to get some time to address this. 

To address this I have been considering to move to ZXing js based library and have created a prototype in `beta-zxing` branch. Based on my testing the library seems to be able to scan the QR code you have shared reliably.
 
You can try out the demo here: https://blog.minhazav.dev/research/html5-qrcode-beta 
Here's the minified code to experiment with: [link to minified js](https://raw.githubusercontent.com/mebjas/html5-qrcode/beta-zxing/minified/html5-qrcode.min.js)

Can you try out the beta demo with similar QR codes and share if you find any issues? If the results look good, I'll move the underlying code base to use `ZXing`. It comes with some extra benefits like support for barcode etc but requires some refactor but the cost benefit seems good.

**Comment by BenTalagan** [comment] 2020-11-30 21:05
Hi @mebjas, and thanks a lot for the hard work and huge effort on this lib and for maintaining it! This is a major, if not the biggest issue in your framework. Reliability is critical for some applications :) 

The new branch using `zxing` makes a huge difference for me on my own use cases. For the following QR Code, for example, I get 10% of errors using the stable branch, and could not even make it fail with the `zxing` branch after more than a hundred tries. I'd even say that the stable branch is reliably unreliable among various platforms (after having asked different people to test that qr code under various OS - macos/android/ios, hardwares - macbook/samsung/ios and browsers).

![qrcodedefect2](https://user-images.githubusercontent.com/427791/100664185-929f0b00-3357-11eb-8e44-62988f2f33d2.jpeg)

So it's no contest for me, I'm switching to the new implementation.

**Comment by ygoe** [comment] 2020-11-30 21:15
I haven't gotten around to try the new branch but @BenTalagan 's report sounds very promising. It's good to hear that this can be solved and it makes me more confident that I can implement my planned application with it.

**Comment by Thecreator1** [comment] 2020-12-23 12:40
I solved the issue in the early release by making multiple scan cycles and pushing the decoded value into an array and increment a counter++ on each scan cycle.
Then when the counter reaches a preset number of n scan cycles, extract the mode value of the array, the value that is most common in the array.

**Comment by mebjas** [comment] 2021-06-13 05:39
This issue is now resolved in new versions as we shifted to ZXing libraries. Closing for now, please reopen if the issue is still reproducible **in latest library version** - try with demo page: https://blog.minhazav.dev/research/html5-qrcode

**Closed by mebjas** 2021-06-13 05:39 UTC
Labels: Priority1, help wanted, jsqrcode-bug, reliability
