### ISSUE TITLE
Cannot read a specific QR code

### ISSUE THREAD

**Issue by aminurrashid** [mebjas/html5-qrcode#60] opened 2020-06-11 17:25 UTC
**Describe the bug**
Cannot read a specific QR code, although it is readable in other qr code scanning library/app.

QR code:

<img width="83" alt="qr_config" src="https://user-images.githubusercontent.com/4655668/84418751-6c66a100-ac39-11ea-9f51-3314d662459a.png">

Data of the QR code: "action":"config"

**To Reproduce**
1. Go to https://blog.minhazav.dev/research/html5-qrcode.html
2. Scan the given QR code.

**Expected behavior**
Scan result should show: "action":"config"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.97

**Smartphone (please complete the following information):**
 - Device: Nexus 6P
 - OS: android 8.1.0
 - Browser: Chrome
 - Version: 83.0.4103.96

**Comment by mebjas** [comment] 2020-06-13 06:10
You are right, the scanner is not able to scan this `QR Code` on any platform. This is potentially an issue in the underlying logic that decodes the qr-code of new types - https://github.com/LazarSoft/jsqrcode/issues/33

I'll try to see if I can fix this, thanks for reporting this.

**Comment by mebjas** [comment] 2020-06-13 06:23
![Screenshot 2020-06-13 at 2 06 46 PM](https://user-images.githubusercontent.com/3007365/84561732-74315d00-ad81-11ea-8f7b-fd2d1315ab1c.png)

This is another Qr code the scanner was not able to scan

**Comment by mebjas** [comment] 2020-06-13 06:51
Sent a push which is now able to scan these new codes - https://github.com/mebjas/html5-qrcode/commit/97a3c10373fb72b9eab29f6a9f77898b6fd5f2fc

**Comment by mebjas** [comment] 2020-06-13 06:53
Please feel free to close this issue once you have verified, assigning it to you.

Latest changes published to
 - npm - https://www.npmjs.com/package/html5-qrcode 
 - https://github.com/mebjas/html5-qrcode/releases/tag/V1.1.2
 - https://blog.minhazav.dev/research/html5-qrcode

**Comment by aminurrashid** [comment] 2020-06-14 06:27
not sure if something wrong with the latest build, but I'm getting some weird data for the QR code I've given. I'm getting some results like "actiin":"config", "actimn":"config" and sometimes a weird long number, where the result should be "action":"config".
I've scanned using https://blog.minhazav.dev/research/html5-qrcode. Screenshot of scan result is attached here.

![Screenshot_20200614-121738](https://user-images.githubusercontent.com/4655668/84586319-4e1bc380-ae3a-11ea-95f1-0c65ad541dca.png)

**Comment by mebjas** [comment] 2020-06-21 09:08
I am able to reproduce this issue on the small QR code while it seems to be much more stable or relatively larger one. I am not sure what the library can help here as - it's dependent on processing what the camera sends and then decoding it.

I'd recommend having a logic on your side to try to decode the output you get to see if it matches the expected outcome. Maybe something like
```js
function onScanSuccess(qrCodeMessage) {
  let jsonResponse = `{${qrCodeMessage}}`;
  try {
    let jsonObject = JSON.parse(jsonResponse);
    if ("action" in jsonObject) {
      // do your main action
    }
  } catch (exception) {
    // ignore
  }
}

```

**Comment by mebjas** [comment] 2020-08-02 11:01
Closing this issue as primary issue has been solved and secondary issue has been reported as https://github.com/mebjas/html5-qrcode/issues/63 - let's follow up on the other issue in #63

**Closed by mebjas** 2020-08-02 11:01 UTC
Labels: bug, jsqrcode-bug, verification-needed
