### ISSUE TITLE
Custom CSS for scan box

### ISSUE THREAD

**Issue by jahnavi310** [mebjas/html5-qrcode#449] opened 2022-03-23 18:33 UTC
Hi there,

I am using the pro mode to get a custom overlay for the qr code scanner. I am running into issues on trying to override the CSS for the scan box.

I am for some reason not able to style the qr-shaded-region div, is there a way i can override the CSS for the scan box with something custom?

Thanks in advance

**Comment by YTKowshik** [comment] 2022-03-27 09:52
@jahnavi310 take a look at the issue #429. It may help you.

**Comment by sarukomine** [comment] 2022-10-20 08:33
You can remove them and add your own element with custom class into the scan box element.

```javascript
qrScanner.start(......).then(() => {
    let overlayElement = document.getElementById('qr-shaded-region');
    let childElements = overlayElement.querySelectorAll('div');

    // Remove corners
    for (let childElement of childElements) {
        childElement.remove();
    }

    // Create own corner elements
    let leftTopElement = document.createElement('div');
    let leftBottomElement = document.createElement('div');
    let rightTopElement = document.createElement('div');
    let rightBottomElement = document.createElement('div');

    leftTopElement.classList.add('custom-corners-css');
    leftBottomElement.classList.add('custom-corners-css');
    rightTopElement.classList.add('custom-corners-css');
    rightBottomElement.classList.add('custom-corners-css');

    overlayElement.appendChild(leftTopElement);
    overlayElement.appendChild(leftBottomElement);
    overlayElement.appendChild(rightTopElement);
    overlayElement.appendChild(rightBottomElement);
});
```

**Comment by mebjas** [comment] 2022-10-29 15:57
Marking this as a duplicate of https://github.com/mebjas/html5-qrcode/issues/389

Let's have more discussion there.

**Closed by mebjas** 2022-10-29 15:57 UTC

**Comment by fyrus7** [comment] 2024-10-11 17:17
> You can remove them and add your own element with custom class into the scan box element.
> 
> ```js
> qrScanner.start(......).then(() => {
>     let overlayElement = document.getElementById('qr-shaded-region');
>     let childElements = overlayElement.querySelectorAll('div');
> 
>     // Remove corners
>     for (let childElement of childElements) {
>         childElement.remove();
>     }
> 
>     // Create own corner elements
>     let leftTopElement = document.createElement('div');
>     let leftBottomElement = document.createElement('div');
>     let rightTopElement = document.createElement('div');
>     let rightBottomElement = document.createElement('div');
> 
>     leftTopElement.classList.add('custom-corners-css');
>     leftBottomElement.classList.add('custom-corners-css');
>     rightTopElement.classList.add('custom-corners-css');
>     rightBottomElement.classList.add('custom-corners-css');
> 
>     overlayElement.appendChild(leftTopElement);
>     overlayElement.appendChild(leftBottomElement);
>     overlayElement.appendChild(rightTopElement);
>     overlayElement.appendChild(rightBottomElement);
> });
> ```

Anyone got an idea how to do this? I cant shape the shade region
