### ISSUE TITLE
VIN Barcodes are not scanned

### ISSUE THREAD

**Issue by ramakrishnanjayaraman** [mebjas/html5-qrcode#367] opened 2021-12-13 00:44 UTC
**Describe the bug**
CODE 39 based codes do not appear to be scanned. Especially VIN codes. Tried several VIN on stickers with no reaction whatsoever. 

**To Reproduce**
1. Used HTML5QRCodeScanner
2. Scan VIN barcode
3. VIN is not scanned

**Expected behavior**
VIN barcode should be scanned

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by mebjas** [comment] 2021-12-13 04:01
Please share some samples.

**Comment by ramakrishnanjayaraman** [comment] 2021-12-13 06:05
check the barcode here : 
https://www.dynamsoft.com/blog/imaging/barcode/scanning-vin-codes-barcode-reader/

**Comment by ramakrishnanjayaraman** [comment] 2021-12-14 06:18
@mebjas please advise if you were able to reproduce the issue ?

**Comment by mebjas** [comment] 2021-12-20 05:45
@ramakrishnanjayaraman  I am able to reproduce this issue.

It looks like the code on its own gets scanned by the decoder library. (you can verify this by taking a screenshot and using `file based scan option`). However when scanning with the camera - it doesn't work.

My hypothesis is this is due to the preview being small, the low pass filter used to downsample the input frame looses the information.

![Screenshot 2021-12-20 at 1 42 09 PM](https://user-images.githubusercontent.com/3007365/146717599-eeccb973-2022-4586-b6eb-9b9bd638c4b6.png)

Some ideas that come to mind are:
1. Use a larger canvas to render the frame before decoding
2. Try a rectangular QR code box so we can capture as large VIN area as possible

**Comment by mebjas** [comment] 2021-12-20 05:56
Option 2 seems to be working for me

![image](https://user-images.githubusercontent.com/3007365/146718617-a11b19eb-e7e9-4d6a-87c8-5c25273885ea.png)

Setting following config:

```js
let html5QrcodeScanner = new Html5QrcodeScanner(
  "reader", 
  { 
      fps: 10,
      qrbox: {width: 500, height: 250},
      // Important notice: this is experimental feature, use it at your
      // own risk. See documentation in
      // mebjas@/html5-qrcode/src/experimental-features.ts
      experimentalFeatures: {
          useBarCodeDetectorIfSupported: true
      },
      rememberLastUsedCamera: true,
      aspectRatio: 1.7777778
  });
```

@ramakrishnanjayaraman 
Can you check if this works for you?

**Comment by ramakrishnanjayaraman** [comment] 2021-12-23 00:29
@mebjas thank you so much for your quick reply. This does seem to work better!

**Comment by mebjas** [comment] 2021-12-25 05:15
@ramakrishnanjayaraman Thanks for testing this out. For now I'll close this bug and you can track the other issue for progress.

**Closed by mebjas** 2021-12-25 05:15 UTC
Labels: information-needed
