### ISSUE TITLE
Error reading bordered qrcodes

### ISSUE THREAD

**Issue by FabricioGRodrigues** [mebjas/html5-qrcode#370] opened 2021-12-15 13:12 UTC
I'm using the lib on a project, it works without a problem, but with a specific type of qr, it's not scanned.
I've already added more than one Html5QrcodeSupportedFormats, and even so this specific qr isn't working!

qrcode with problem
![image](https://user-images.githubusercontent.com/2169213/146192492-060b7b9c-b240-419c-a899-4fd67130cf3a.png)

qrcode ok
![image](https://user-images.githubusercontent.com/2169213/146192599-98da7269-7553-4861-aa38-30b579d4b04e.png)

**Comment by ROBERT-MCDOWELL** [comment] 2021-12-15 23:05
@mebjas
is html5-qrcode support inverted qrcode?

**Comment by mebjas** [comment] 2021-12-20 04:50
@FabricioGRodrigues what config and device/browser are you testing with?

I am able to scan this on Pixel but not on Iphone.

**Comment by mebjas** [comment] 2021-12-20 04:50
@ROBERT-MCDOWELL 

> is html5-qrcode support inverted qrcode?
Not the implicit one, but the on device experimental one seems to be able to scan on certain devices.

**Comment by mebjas** [comment] 2021-12-20 05:19
This issues is a duplicate of https://github.com/mebjas/html5-qrcode/issues/94 - please follow the thread there, I'll likely add the support soon.

**Comment by mebjas** [comment] 2021-12-20 05:19
Closing this ticket.

**Closed by mebjas** 2021-12-20 05:19 UTC

**Comment by FabricioGRodrigues** [comment] 2021-12-20 12:51
@mebjas 

I tested it on a samsung A750,A20,A30,Iphone 13 and using Google Chrome browser Version 96.0.4664.110. Using normal library installation setup (html5-qrcode).
The qrcodes without the dark background worked without any problem on all devices!
