### ISSUE TITLE
vue the import prompt is not defined

### ISSUE THREAD

**Issue by lintiansheng** [mebjas/html5-qrcode#48] opened 2020-05-20 08:34 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mebjas** [comment] 2020-05-22 16:34
Closing as duplicate of https://github.com/mebjas/html5-qrcode/issues/49

**Closed by mebjas** 2020-05-22 16:34 UTC
